name: Bug report
description: Report a bug in the Android SDK
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: Clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Reproduction steps
      description: How can we reproduce this?
      placeholder: |
        1. Initialize SDK with ...
        2. Trigger ...
        3. Observe ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior / logs
      description: Include stack traces, logs, and screenshots if useful.
    validations:
      required: false

  - type: input
    id: sdk_version
    attributes:
      label: SDK version
      placeholder: "0.2.0"
    validations:
      required: true

  - type: input
    id: android_version
    attributes:
      label: Android API level / OS version
      placeholder: "API 33 / Android 13"
    validations:
      required: true

  - type: input
    id: kotlin_agp
    attributes:
      label: Kotlin + AGP versions
      placeholder: "Kotlin 2.1.10, AGP 8.8.2"
    validations:
      required: false
