name: Feature request
description: Suggest an enhancement for the Android SDK
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: Describe the API/behavior you want.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternatives or workarounds?
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Links, examples, or screenshots.
    validations:
      required: false
